schema_version: '2.0'
uid: 6af4b5ac-b2a0-4a1f-918f-f2346405970a
pipeline_id: 0004_config_df13ed
name: config_df13ed
dataset: hiba23
created_at: '2026-01-15T18:55:39.891377+00:00'
pipeline:
  steps:
  - nirs4all.operators.transforms.scalers.StandardNormalVariate
  - class: sklearn.model_selection._split.KFold
    params:
      n_splits: 3
  - model:
      class: sklearn.cross_decomposition._pls.PLSRegression
      params:
        n_components: 5
generator_choices: []
metadata: {}
dataset_info: {}
artifacts:
  schema_version: '2.0'
  items:
  - artifact_id: 0004_config_df13ed$2944da1daa16:all
    content_hash: sha256:f1b0d49d100fdce0b1f766631a2fc34c1b2477ed43ee4a120b8aedc3581c1d26
    path: transformer_StandardNormalVariate_f1b0d49d100f.joblib
    chain_path: s1.StandardNormalVariate[src=0,sub=0]
    source_index: 0
    pipeline_id: 0004_config_df13ed
    branch_path: []
    step_index: 1
    substep_index: 0
    fold_id: null
    artifact_type: transformer
    class_name: StandardNormalVariate
    custom_name: ''
    depends_on: []
    format: joblib
    format_version: ''
    nirs4all_version: 0.6.2
    size_bytes: 132
    created_at: '2026-01-15T18:55:39.908693+00:00'
    params: {}
    version: 3
  - artifact_id: 0004_config_df13ed$2d4cd0b32aa0:0
    content_hash: sha256:b1004b2249ec69887751a9097ee7b889e9ca2a2a38729812666b0652e3a7c318
    path: model_PLSRegression_b1004b2249ec.joblib
    chain_path: s3.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0004_config_df13ed
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: 0
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLSRegression
    depends_on: []
    format: joblib
    format_version: sklearn==1.8.0
    nirs4all_version: 0.6.2
    size_bytes: 340621
    created_at: '2026-01-15T18:55:41.158077+00:00'
    params: {}
    version: 3
  - artifact_id: 0004_config_df13ed$2d4cd0b32aa0:1
    content_hash: sha256:b0cf69657b575d5b3aca83b0286b47aa3f08c6ab21ed1a1a038ef063f1598daa
    path: model_PLSRegression_b0cf69657b57.joblib
    chain_path: s3.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0004_config_df13ed
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: 1
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLSRegression
    depends_on: []
    format: joblib
    format_version: sklearn==1.8.0
    nirs4all_version: 0.6.2
    size_bytes: 340909
    created_at: '2026-01-15T18:55:41.177980+00:00'
    params: {}
    version: 3
  - artifact_id: 0004_config_df13ed$2d4cd0b32aa0:2
    content_hash: sha256:7fdb071cee736fbc6444f6ddeb2d9eaf859887cc6895ca68d78b8f55649f4217
    path: model_PLSRegression_7fdb071cee73.joblib
    chain_path: s3.PLSRegression[sub=0]
    source_index: null
    pipeline_id: 0004_config_df13ed
    branch_path: []
    step_index: 3
    substep_index: 0
    fold_id: 2
    artifact_type: model
    class_name: PLSRegression
    custom_name: PLSRegression
    depends_on: []
    format: joblib
    format_version: sklearn==1.8.0
    nirs4all_version: 0.6.2
    size_bytes: 340885
    created_at: '2026-01-15T18:55:41.187750+00:00'
    params: {}
    version: 3
predictions: []
execution_traces:
  075a7ff7-229:
    trace_id: 075a7ff7-229
    pipeline_uid: 0004_config_df13ed
    created_at: '2026-01-15T18:55:39.892149+00:00'
    steps:
    - step_index: 1
      operator_type: transform
      operator_class: StandardNormalVariate
      operator_config: {}
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0004_config_df13ed$2944da1daa16:all
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0004_config_df13ed$2944da1daa16:all
        by_source:
          0:
          - 0004_config_df13ed$2944da1daa16:all
        by_chain:
          s1.StandardNormalVariate[src=0,sub=0]: 0004_config_df13ed$2944da1daa16:all
        metadata:
          class_name: StandardNormalVariate
          name: StandardNormalVariate_1
      branch_path: []
      branch_name: ''
      duration_ms: 30.167341232299805
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s1.StandardNormalVariate[src=0,sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 596
      - 2151
      output_shape:
      - 596
      - 2151
      input_features_shape:
      - - 596
        - 1
        - 2151
      output_features_shape:
      - - 596
        - 1
        - 2151
    - step_index: 2
      operator_type: splitter
      operator_class: KFold
      operator_config:
        class: sklearn.model_selection._split.KFold
        params:
          n_splits: 3
      execution_mode: train
      artifacts:
        artifact_ids: []
        primary_artifact_id: null
        fold_artifact_ids: {}
        primary_artifacts: {}
        by_branch: {}
        by_source: {}
        by_chain: {}
        metadata: {}
      branch_path: []
      branch_name: ''
      duration_ms: 17.244815826416016
      metadata: {}
      input_chain_path: ''
      output_chain_paths: []
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 596
      - 2151
      output_shape:
      - 596
      - 2151
      input_features_shape:
      - - 596
        - 1
        - 2151
      output_features_shape:
      - - 596
        - 1
        - 2151
    - step_index: 3
      operator_type: model
      operator_class: PLSRegression
      operator_config:
        model:
          class: sklearn.cross_decomposition._pls.PLSRegression
          params:
            n_components: 5
      execution_mode: train
      artifacts:
        artifact_ids:
        - 0004_config_df13ed$2d4cd0b32aa0:0
        - 0004_config_df13ed$2d4cd0b32aa0:1
        - 0004_config_df13ed$2d4cd0b32aa0:2
        primary_artifact_id: null
        fold_artifact_ids:
          0: 0004_config_df13ed$2d4cd0b32aa0:0
          1: 0004_config_df13ed$2d4cd0b32aa0:1
          2: 0004_config_df13ed$2d4cd0b32aa0:2
        primary_artifacts: {}
        by_branch:
          ? ''
          : - 0004_config_df13ed$2d4cd0b32aa0:0
            - 0004_config_df13ed$2d4cd0b32aa0:1
            - 0004_config_df13ed$2d4cd0b32aa0:2
        by_source: {}
        by_chain:
          s3.PLSRegression[sub=0]: 0004_config_df13ed$2d4cd0b32aa0:2
        metadata:
          class_name: PLSRegression
          custom_name: PLSRegression
      branch_path: []
      branch_name: ''
      duration_ms: 1410.05539894104
      metadata: {}
      input_chain_path: ''
      output_chain_paths:
      - s3.PLSRegression[sub=0]
      source_count: 1
      produces_branches: false
      substep_index: null
      input_shape:
      - 596
      - 2151
      output_shape:
      - 596
      - 2151
      input_features_shape:
      - - 596
        - 1
        - 2151
      output_features_shape:
      - - 596
        - 1
        - 2151
    model_step_index: 3
    fold_weights: null
    preprocessing_chain: SNV
    metadata:
      dataset: hiba23
      config_name: config_df13ed
      n_steps: 3
      n_artifacts: 4
