import { useState, useEffect, useMemo } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion } from "@/lib/motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import {
  InlineLoading,
  InlineError,
  NoDatasetsState,
  NoPipelinesState,
} from "@/components/ui/state-display";
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Database,
  GitBranch,
  Play,
  Star,
  Search,
  Filter,
  Loader2,
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { listDatasets, listPipelines, createRun } from "@/api/client";
import type { Dataset } from "@/types/datasets";
import type { PipelineInfo } from "@/api/client";
import type { ExperimentConfig } from "@/types/runs";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

// Helper to summarize pipeline steps
function summarizePipelineSteps(steps: PipelineInfo["steps"]): string {
  if (!steps || steps.length === 0) return "Empty pipeline";
  return steps.map(s => s.name).join(" → ");
}

const wizardSteps = [
  { id: 1, label: "Select Datasets", icon: Database },
  { id: 2, label: "Select Pipelines", icon: GitBranch },
  { id: 3, label: "Review", icon: Check },
  { id: 4, label: "Launch", icon: Play },
];

export default function NewExperiment() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const queryClient = useQueryClient();
  const [currentStep, setCurrentStep] = useState(1);
  const [customExperimentName, setCustomExperimentName] = useState("");
  const [experimentDescription, setExperimentDescription] = useState("");
  const [selectedDatasets, setSelectedDatasets] = useState<string[]>([]);
  const [selectedPipelines, setSelectedPipelines] = useState<string[]>([]);
  const [datasetSearch, setDatasetSearch] = useState("");
  const [pipelineSearch, setPipelineSearch] = useState("");
  const [pipelineFilter, setPipelineFilter] = useState<
    "all" | "favorites" | "presets"
  >("all");

  // Current edited pipeline from editor (unsaved)
  const [currentEditedPipeline, setCurrentEditedPipeline] = useState<{
    id?: string;
    name: string;
    steps: unknown[];
    isDirty: boolean;
  } | null>(null);

  // Fetch datasets from API
  const { data: datasetsData, isLoading: loadingDatasets, error: datasetsError } = useQuery({
    queryKey: ["datasets"],
    queryFn: async () => {
      const response = await listDatasets();
      return response;
    },
  });

  // Fetch pipelines from API
  const { data: pipelinesData, isLoading: loadingPipelines, error: pipelinesError } = useQuery({
    queryKey: ["pipelines"],
    queryFn: async () => {
      const response = await listPipelines();
      return response;
    },
  });

  // Transform datasets to display format
  const datasets = (datasetsData?.datasets || []).map((d: Dataset) => ({
    id: d.id,
    name: d.name || d.path?.split("/").pop() || "Unknown",
    samples: d.num_samples || 0,
    features: d.num_features || 0,
    target: d.default_target || d.targets?.[0]?.column || "Unknown",
  }));

  // Transform pipelines to display format
  const pipelines = (pipelinesData?.pipelines || []).map((p: PipelineInfo) => ({
    id: p.id,
    name: p.name,
    preset: p.category === "preset",
    favorite: p.is_favorite || false,
    steps: summarizePipelineSteps(p.steps),
  }));

  // Combined pipelines including current edited pipeline if available
  const allPipelines = useMemo(() => {
    if (currentEditedPipeline) {
      const editedEntry = {
        id: "__current_edited__",
        name: `📝 ${currentEditedPipeline.name}${currentEditedPipeline.isDirty ? " (unsaved)" : ""}`,
        preset: false,
        favorite: false,
        steps: "Current edited pipeline from editor",
        isCurrentEdited: true,
      };
      return [editedEntry, ...pipelines];
    }
    return pipelines;
  }, [pipelines, currentEditedPipeline]);

  // Auto-generate experiment name based on selected datasets and pipelines
  const autoGeneratedName = useMemo(() => {
    const datasetNames = selectedDatasets
      .map(id => datasets.find(d => d.id === id)?.name)
      .filter(Boolean);
    const pipelineNames = selectedPipelines
      .map(id => {
        if (id === "__current_edited__") return currentEditedPipeline?.name;
        return allPipelines.find(p => p.id === id)?.name;
      })
      .filter(Boolean);

    if (datasetNames.length === 0 || pipelineNames.length === 0) return "";

    const datasetPart = datasetNames.length === 1
      ? datasetNames[0]
      : `${datasetNames.length} datasets`;
    const pipelinePart = pipelineNames.length === 1
      ? pipelineNames[0]
      : `${pipelineNames.length} pipelines`;

    return `${datasetPart} - ${pipelinePart}`;
  }, [selectedDatasets, selectedPipelines, datasets, allPipelines, currentEditedPipeline]);

  // Use custom name if provided, otherwise use auto-generated name
  const experimentName = customExperimentName.trim() || autoGeneratedName;

  // Handle auto-selection from pipeline editor
  useEffect(() => {
    const pipelineId = searchParams.get('pipeline');
    const source = searchParams.get('source');

    if (source === 'editor') {
      // Load current edited pipeline from sessionStorage
      try {
        const stored = sessionStorage.getItem('current-edited-pipeline');
        if (stored) {
          const data = JSON.parse(stored);
          setCurrentEditedPipeline({
            id: data.id,
            name: data.name,
            steps: data.steps,
            isDirty: data.isDirty,
          });
          // Auto-select the current edited pipeline
          setSelectedPipelines(["__current_edited__"]);
          toast.info(`Pipeline "${data.name}" ready for experiment`);
          // Clear the stored data
          sessionStorage.removeItem('current-edited-pipeline');
        }
      } catch (e) {
        console.error('Failed to load current edited pipeline:', e);
      }
      // Clean up URL
      navigate('/editor', { replace: true });
    } else if (pipelineId && pipelinesData?.pipelines) {
      // Check if the pipeline exists in the loaded pipelines
      const exists = pipelinesData.pipelines.some(p => p.id === pipelineId);
      if (exists && !selectedPipelines.includes(pipelineId)) {
        setSelectedPipelines([pipelineId]);
        const pipeline = pipelinesData.pipelines.find(p => p.id === pipelineId);
        if (pipeline) {
          toast.info(`Pipeline "${pipeline.name}" selected`);
        }
      }
      // Clean up URL
      navigate('/editor', { replace: true });
    }
  }, [searchParams, pipelinesData, navigate]); // Intentionally not including selectedPipelines

  const toggleDataset = (id: string) => {
    setSelectedDatasets((prev) =>
      prev.includes(id) ? prev.filter((d) => d !== id) : [...prev, id]
    );
  };

  const togglePipeline = (id: string) => {
    setSelectedPipelines((prev) =>
      prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id]
    );
  };

  const filteredDatasets = datasets.filter((d) =>
    d.name.toLowerCase().includes(datasetSearch.toLowerCase())
  );

  const filteredPipelines = allPipelines.filter((p) => {
    const matchesSearch =
      p.name.toLowerCase().includes(pipelineSearch.toLowerCase()) ||
      p.steps.toLowerCase().includes(pipelineSearch.toLowerCase());
    // Current edited pipeline is always shown in "all" filter
    if ("isCurrentEdited" in p && p.isCurrentEdited) {
      return matchesSearch;
    }
    if (pipelineFilter === "favorites") return matchesSearch && p.favorite;
    if (pipelineFilter === "presets") return matchesSearch && p.preset;
    return matchesSearch;
  });

  const canProceed = () => {
    if (currentStep === 1) return selectedDatasets.length > 0;
    if (currentStep === 2) return selectedPipelines.length > 0;
    // Step 3 always proceeds since name is auto-generated
    return true;
  };

  const totalRuns = selectedDatasets.length * selectedPipelines.length;

  // Create run mutation
  const createRunMutation = useMutation({
    mutationFn: async (config: ExperimentConfig) => {
      return createRun(config);
    },
    onSuccess: (run) => {
      toast.success("Experiment started!");
      // Invalidate runs cache
      queryClient.invalidateQueries({ queryKey: ["runs"] });
      // Navigate to run progress page
      navigate(`/runs/${run.id}`);
    },
    onError: (error) => {
      toast.error(`Failed to start: ${error instanceof Error ? error.message : "Unknown error"}`);
    },
  });

  const handleLaunch = () => {
    // Filter out the current edited pipeline and handle it separately
    const regularPipelineIds = selectedPipelines.filter(id => id !== "__current_edited__");
    const hasCurrentEdited = selectedPipelines.includes("__current_edited__");

    const config: ExperimentConfig = {
      name: experimentName,
      description: experimentDescription || undefined,
      dataset_ids: selectedDatasets,
      pipeline_ids: regularPipelineIds,
      // Include inline pipeline if current edited pipeline is selected
      inline_pipeline: hasCurrentEdited && currentEditedPipeline ? {
        name: currentEditedPipeline.name,
        steps: currentEditedPipeline.steps,
      } : undefined,
    };
    createRunMutation.mutate(config);
  };

  return (
    <motion.div
      className="space-y-6"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      {/* Header */}
      <motion.div variants={itemVariants} className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => navigate("/runs")}>
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">New Experiment</h1>
          <p className="text-muted-foreground">
            Create and launch pipeline experiments
          </p>
        </div>
      </motion.div>

      {/* Step Indicator */}
      <motion.div
        variants={itemVariants}
        className="flex items-center justify-between max-w-2xl mx-auto"
      >
        {wizardSteps.map((step, index) => {
          const StepIcon = step.icon;
          const isActive = step.id === currentStep;
          const isCompleted = step.id < currentStep;
          return (
            <div key={step.id} className="flex items-center">
              <div className="flex flex-col items-center">
                <div
                  className={cn(
                    "w-10 h-10 rounded-full flex items-center justify-center border-2 transition-colors",
                    isActive
                      ? "border-primary bg-primary text-primary-foreground"
                      : isCompleted
                      ? "border-chart-1 bg-chart-1 text-primary-foreground"
                      : "border-border bg-card text-muted-foreground"
                  )}
                >
                  {isCompleted ? (
                    <Check className="h-5 w-5" />
                  ) : (
                    <StepIcon className="h-5 w-5" />
                  )}
                </div>
                <span
                  className={cn(
                    "text-xs mt-2",
                    isActive
                      ? "text-foreground font-medium"
                      : "text-muted-foreground"
                  )}
                >
                  {step.label}
                </span>
              </div>
              {index < wizardSteps.length - 1 && (
                <div
                  className={cn(
                    "w-24 h-0.5 mx-2",
                    isCompleted ? "bg-chart-1" : "bg-border"
                  )}
                />
              )}
            </div>
          );
        })}
      </motion.div>

      {/* Step Content */}
      <motion.div variants={itemVariants}>
        <Card className="max-w-4xl mx-auto">
          <CardContent className="p-6">
            {/* Step 1: Select Datasets */}
            {currentStep === 1 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold text-foreground">
                    Select Datasets
                  </h2>
                  <Badge variant="secondary">
                    {selectedDatasets.length} selected
                  </Badge>
                </div>
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Search datasets..."
                    value={datasetSearch}
                    onChange={(e) => setDatasetSearch(e.target.value)}
                    className="pl-9"
                  />
                </div>

                {/* Loading state */}
                {loadingDatasets && <InlineLoading message="Loading datasets..." />}

                {/* Error state */}
                {datasetsError && (
                  <InlineError message={datasetsError instanceof Error ? datasetsError.message : "Failed to load datasets"} />
                )}

                {/* Empty state - no workspace or no datasets */}
                {!loadingDatasets && !datasetsError && datasets.length === 0 && (
                  <NoDatasetsState
                    title="No datasets available"
                    description="Link a workspace with datasets in Settings, or import a dataset."
                    actionLabel="Go to Settings"
                    actionPath="/settings"
                  />
                )}

                {/* Dataset list */}
                {!loadingDatasets && !datasetsError && datasets.length > 0 && (
                  <div className="space-y-2 max-h-80 overflow-y-auto">
                    {filteredDatasets.map((dataset) => (
                      <div
                        key={dataset.id}
                        onClick={() => toggleDataset(dataset.id)}
                        className={cn(
                          "p-4 border rounded-lg cursor-pointer transition-colors",
                          selectedDatasets.includes(dataset.id)
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-primary/50"
                        )}
                      >
                        <div className="flex items-center gap-3">
                          <Checkbox
                            checked={selectedDatasets.includes(dataset.id)}
                            onCheckedChange={() => toggleDataset(dataset.id)}
                          />
                          <div className="flex-1">
                            <p className="font-medium text-foreground">
                              {dataset.name}
                            </p>
                            <p className="text-sm text-muted-foreground">
                              {dataset.samples} samples • {dataset.features}{" "}
                              features • Target: {dataset.target}
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                    {filteredDatasets.length === 0 && datasetSearch && (
                      <div className="text-center py-4 text-muted-foreground">
                        No datasets match "{datasetSearch}"
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Step 2: Select Pipelines */}
            {currentStep === 2 && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-semibold text-foreground">
                    Select Pipelines
                  </h2>
                  <Badge variant="secondary">
                    {selectedPipelines.length} selected
                  </Badge>
                </div>
                <div className="flex gap-3">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder="Search pipelines..."
                      value={pipelineSearch}
                      onChange={(e) => setPipelineSearch(e.target.value)}
                      className="pl-9"
                    />
                  </div>
                  <Select
                    value={pipelineFilter}
                    onValueChange={(v: "all" | "favorites" | "presets") =>
                      setPipelineFilter(v)
                    }
                  >
                    <SelectTrigger className="w-40">
                      <Filter className="h-4 w-4 mr-2" />
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Pipelines</SelectItem>
                      <SelectItem value="favorites">Favorites</SelectItem>
                      <SelectItem value="presets">Presets</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Loading state */}
                {loadingPipelines && <InlineLoading message="Loading pipelines..." />}

                {/* Error state */}
                {pipelinesError && (
                  <InlineError message={pipelinesError instanceof Error ? pipelinesError.message : "Failed to load pipelines"} />
                )}

                {/* Empty state */}
                {!loadingPipelines && !pipelinesError && pipelines.length === 0 && (
                  <NoPipelinesState
                    title="No pipelines available"
                    description="Create a pipeline in the Pipeline Editor first."
                    actionLabel="Create Pipeline"
                    actionPath="/pipelines/new"
                  />
                )}

                {/* Pipeline list */}
                {!loadingPipelines && !pipelinesError && pipelines.length > 0 && (
                  <div className="space-y-2 max-h-80 overflow-y-auto">
                    {filteredPipelines.map((pipeline) => (
                      <div
                        key={pipeline.id}
                        onClick={() => togglePipeline(pipeline.id)}
                        className={cn(
                          "p-4 border rounded-lg cursor-pointer transition-colors",
                          selectedPipelines.includes(pipeline.id)
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-primary/50"
                        )}
                      >
                        <div className="flex items-center gap-3">
                          <Checkbox
                            checked={selectedPipelines.includes(pipeline.id)}
                            onCheckedChange={() => togglePipeline(pipeline.id)}
                          />
                          <div className="flex-1">
                            <div className="flex items-center gap-2">
                              <p className="font-medium text-foreground">
                                {pipeline.name}
                              </p>
                              {pipeline.favorite && (
                                <Star className="h-3 w-3 fill-chart-2 text-chart-2" />
                              )}
                              {pipeline.preset && (
                                <Badge variant="outline" className="text-xs">
                                  Preset
                                </Badge>
                              )}
                            </div>
                            <code className="text-sm text-muted-foreground">
                              {pipeline.steps}
                            </code>
                          </div>
                        </div>
                      </div>
                    ))}
                    {filteredPipelines.length === 0 && pipelineSearch && (
                      <div className="text-center py-4 text-muted-foreground">
                        No pipelines match "{pipelineSearch}"
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Step 3: Review */}
            {currentStep === 3 && (
              <div className="space-y-6">
                <h2 className="text-lg font-semibold text-foreground">
                  Review Experiment
                </h2>
                <Card className="bg-muted/30">
                  <CardContent className="p-4">
                    <div className="space-y-4">
                      <div>
                        <label className="text-sm text-muted-foreground">Experiment Name</label>
                        <Input
                          value={customExperimentName}
                          onChange={(e) => setCustomExperimentName(e.target.value)}
                          placeholder={autoGeneratedName}
                          className="mt-1"
                        />
                      </div>
                      <div className="grid grid-cols-3 gap-4 text-sm">
                        <div>
                          <span className="text-muted-foreground">Datasets</span>
                          <p className="font-semibold text-foreground">
                            {selectedDatasets.length}
                          </p>
                        </div>
                        <div>
                          <span className="text-muted-foreground">Pipelines</span>
                          <p className="font-semibold text-foreground">
                            {selectedPipelines.length}
                          </p>
                        </div>
                        <div>
                          <span className="text-muted-foreground">Total Runs</span>
                          <p className="font-semibold text-foreground">
                            {totalRuns}
                          </p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <div>
                  <label className="text-sm font-medium text-foreground">
                    Description (optional)
                  </label>
                  <Textarea
                    value={experimentDescription}
                    onChange={(e) => setExperimentDescription(e.target.value)}
                    placeholder="Add notes about this experiment..."
                    className="mt-1.5"
                    rows={2}
                  />
                </div>
              </div>
            )}

            {/* Step 4: Launch */}
            {currentStep === 4 && (
              <div className="space-y-6 text-center py-8">
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto">
                  <Play className="h-8 w-8 text-primary" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-foreground">
                    {experimentName}
                  </h2>
                  {experimentDescription && (
                    <p className="text-sm text-muted-foreground mt-1 max-w-md mx-auto">
                      {experimentDescription}
                    </p>
                  )}
                  <p className="text-muted-foreground mt-2">
                    {totalRuns} runs across {selectedDatasets.length} datasets
                    and {selectedPipelines.length} pipelines
                  </p>
                </div>
                <div className="flex flex-wrap justify-center gap-2">
                  {selectedDatasets.map((id) => {
                    const dataset = datasets.find((d) => d.id === id);
                    return (
                      <Badge key={id} variant="secondary">
                        {dataset?.name || id}
                      </Badge>
                    );
                  })}
                </div>
                <Button
                  size="lg"
                  onClick={handleLaunch}
                  disabled={createRunMutation.isPending}
                >
                  {createRunMutation.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Starting...
                    </>
                  ) : (
                    <>
                      <Play className="h-4 w-4 mr-2" />
                      Launch Experiment
                    </>
                  )}
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </motion.div>

      {/* Navigation */}
      {currentStep < 4 && (
        <motion.div
          variants={itemVariants}
          className="flex justify-between max-w-4xl mx-auto"
        >
          <Button
            variant="outline"
            onClick={() => setCurrentStep((prev) => Math.max(1, prev - 1))}
            disabled={currentStep === 1}
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <Button
            onClick={() => setCurrentStep((prev) => Math.min(4, prev + 1))}
            disabled={!canProceed()}
          >
            Next
            <ArrowRight className="h-4 w-4 ml-2" />
          </Button>
        </motion.div>
      )}
    </motion.div>
  );
}
